image: node:16.8.0-buster

variables:

stages:
  - build
  - approve
  - deploy

build:
  stage: build
  only:
    - main
    - tags
  script:
    # Copy environment variables to .env
    - | 
      if [[ $CI_COMMIT_REF_NAME == "main" ]]
      then 
        cp $DEV_ENV_VARS .env
      elif [[ -n $CI_COMMIT_TAG ]]
      then
        cp $PROD_ENV_VARS .env
      else
        echo "Invalid branch or no tag found"
        exit 1
      fi
    - source .env
    # Install NextJS deps
    - npm ci --silent
    # Build app and run postbuild (next-sitemap)
    - npm run build && npm run postbuild
    # CDK synth (also bundles the app)
    - cd deploy
    - npm ci --silent
    - | 
      if [[ -n $CI_COMMIT_TAG ]]
      then 
        ENVIRONMENT=production npx cdk synth
      else 
        npx cdk synth
      fi
  artifacts:
    paths:
      - node_modules
      - deploy/node_modules
      - deploy/cdk.out
      - .serverless_nextjs

development:
  stage: deploy
  only:
    - main
  dependencies:
    - build
  environment:
    name: dev
    url: https://dev.mutatio.digital
  script:
    - mkdir ~/.aws
    - cp $AWS_CONFIG ~/.aws/config
    - cp $AWS_CREDENTIALS ~/.aws/credentials
    # CDK deploy
    - cd deploy
    - npx cdk deploy --require-approval never --verbose --app 'cdk.out/' Mutatio/Website

approve:
  stage: approve
  only:
    - tags
  except:
    - branches
  environment:
    name: prod
    url: https://mutatio.digital
  when: manual
  script:
    - echo ''
  allow_failure: false

production:
  stage: deploy
  only:
    - tags
  except:
    - branches
  dependencies:
    - build
  environment:
    name: prod
    url: https://mutatio.digital
  script:
    - mkdir ~/.aws
    - cp $AWS_CONFIG ~/.aws/config
    - cp $AWS_CREDENTIALS ~/.aws/credentials
    # CDK deploy
    - cd deploy
    - ENVIRONMENT=production npx cdk deploy --require-approval never --verbose --app 'cdk.out/' Mutatio/Website
