# serverless.yml
edintheclouds-blog:
  component: "@sls-next/serverless-component"
  inputs:
    bucketName: "edintheclouds-blog-nextjs"
    bucketRegion: "eu-west-2"
    domain: "edintheclouds.io"
    domainType: "both"
    domainRedirects:
      www.edintheclouds.io: https://edintheclouds.io
    certificateArn: "arn:aws:acm:us-east-1:146864147024:certificate/c67f0d0c-c895-49ef-a562-ade05ff3de2b"
    