module.exports = {
  mode: 'jit',
  purge: [
    './src/pages/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/layout/*.{js,ts,jsx,tsx}',
  ],
  darkMode: false,
  theme: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    extend: {
      colors: {
        purple: '#1a1762',
        cyan: '#29D4E2',
        turqoise: '#26A3C1',
        navy: '#1B1862',
        ocean: '#20528A',
        paleblue: '#EAF3F9',
        lightblue: '#33ABDF',
        blue: '#127DB8',
        darkblue: '#1B1464',
        darkgray: '#5B5B5B',
      },
    },
  },
  variants: {},
  plugins: [],
};
