name: Deploy to AWS

on:
  push:
    paths:
      - src/**
    # Pushes to main will trigger a development release to the development account.
    branches:
     - main
    # Tags indicate that this is a production release, and will be deployed to the production account.
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Copy repository secrets to env file
        env:
          DEV_ENV_VARS: ${{ secrets.DEV_ENV_VARS }}
          PROD_ENV_VARS: ${{ secrets.PROD_ENV_VARS }}
        run: |
          if [[ $GITHUB_REF_TYPE == "tag" ]]
          then 
            echo $PROD_ENV_VARS | base64 -d > .env
          elif [[ $GITHUB_REF_TYPE == "branch" ]]
          then
            echo $DEV_ENV_VARS | base64 -d > .env
          else
            echo "Invalid branch or no tag found"
            exit 1
          fi
          source .env
      - name: Install dependencies
        run: npm ci --silent
      - name: Build app and run postbuild (next-sitemap)
        run: npm run build && npm run postbuild
      - name: CDK synth
        run: |
          cd deploy
          npm ci --silent
          if [[ $GITHUB_REF_TYPE == "tag" ]]
          then 
            ENVIRONMENT=production npx cdk synth
          else 
            npx cdk synth
          fi
      - name: Compress bundle
        run: tar czf build.tar.gz .serverless_nextjs
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Extract build artifact
        run: tar xzf build.tar.gz
      - name: Setup AWS configuration
        env:
          AWS_CONFIG: ${{ secrets.AWS_CONFIG }}
          AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
        run: |
          mkdir ~/.aws
          echo $AWS_CONFIG | base64 -d > ~/.aws/config
          cat ~/.aws/config
          echo $AWS_CREDENTIALS | base64 -d > ~/.aws/credentials
          cat ~/.aws/credentials
      - name: Deploy NextJS app
        run: |
          cd deploy
          if [[ $GITHUB_REF_TYPE == "tag" ]]
          then
            ENVIRONMENT=production npx cdk deploy --require-approval never --verbose --app 'cdk.out/' EdintheClouds/Website
          else
            npx cdk deploy --require-approval never --verbose --app 'cdk.out/' EdintheClouds/Website
          fi
