name: Deploy

on:
  push:
    branches:
     - main
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Copy environment variables into working directory
        run: |
          if [[ $GITHUB_REF_TYPE == "tag" ]]
          then 
            echo $PROD_ENV_VARS > .env
            echo $(cat .env)
          elif [[ $GITHUB_REF_TYPE == "branch" ]]
          then
            echo $DEV_ENV_VARS > .env
            cat .env
            echo $(cat .env)
          else
            echo "Invalid branch or no tag found"
            exit 1
          fi
      - run: |
          cat .env
          echo $(cat .env)
      - run: source .env
      - name: Install dependencies
        run: npm ci --silent
      - name: Build app and run postbuild (next-sitemap)
        run: npm run build && npm run postbuild
      - name: CDK synth
        run: |
          cd deploy
          npm ci --silent
          if [[ $GITHUB_REF_TYPE == "tag" ]]
          then 
            ENVIRONMENT=production npx cdk synth
          else 
            npx cdk synth
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: |
            node_modules
            deploy/node_modules
            deploy/cdk.out
            .serverless_nextjs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Download artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: .
      - name: Setup AWS configuration
        run: |
          mkdir ~/.aws
          echo $AWS_CONFIG > ~/.aws/config
          cat ~/.aws/config
          echo $AWS_CREDENTIALS > ~/.aws/credentials
          cat ~/.aws/credentials
      - name: Deploy NextJS app
        run: |
          cd deploy
          if [[ $GITHUB_REF_TYPE == "tag" ]]
          then
            ENVIRONMENT=production npx cdk deploy --require-approval never --verbose --app 'cdk.out/' EdintheClouds/Website
          else
            npx cdk deploy --require-approval never --verbose --app 'cdk.out/' EdintheClouds/Website
          fi
